/**
 * AeroSense microinteractions — reading aids only.
 * Citation peek · Evidence-status peek · What-to-notice · Before/After · Evidence trail
 * No external libraries. Progressive enhancement; JS-off keeps semantic HTML usable.
 */
(function () {
  "use strict";

  var STATUS_DEFS = {
    data: {
      label: "DATA",
      def: "Primary measurements, tables, or files generated by this team. Claims must match what the linked artifact shows.",
    },
    design: {
      label: "DESIGN",
      def: "Team-authored architecture, schematic, construct map, or planned method — not a measured performance result.",
    },
    literature: {
      label: "LITERATURE",
      def: "Support comes from published sources or datasheets. Cite the reference; do not treat it as AeroSense validation.",
    },
    prototype: {
      label: "PROTOTYPE",
      def: "Built or implemented in hardware/software/wet lab, but not yet fully validated for the claim it supports.",
    },
    validated: {
      label: "VALIDATED",
      def: "Reserved for claims with completed, documented validation against a stated criterion. Do not invent this label.",
    },
    planned: {
      label: "PLANNED",
      def: "Future work that has not been completed. Never promote Planned to Prototype or Validated without new evidence.",
    },
    concept: {
      label: "CONCEPT",
      def: "Illustrative or conceptual material for orientation. Not experimental data and not a performance claim.",
    },
  };

  var reduceMotion =
    typeof window.matchMedia === "function" &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  var canHover =
    typeof window.matchMedia === "function" &&
    window.matchMedia("(hover: hover)").matches;

  var statusPopover = null;
  var activeStatus = null;
  var statusHoverTimer = null;
  var openCiteWrap = null;

  function textOf(el) {
    return el ? (el.textContent || "").replace(/\s+/g, " ").trim() : "";
  }

  function doiText(el) {
    if (!el) return "";
    var link = el.querySelector("a");
    if (link) return (link.textContent || "").trim();
    return textOf(el).replace(/^DOI:\s*/i, "");
  }

  function venueText(el) {
    if (!el) return "";
    return textOf(el);
  }

  function yearText(el) {
    var raw = textOf(el);
    var m = raw.match(/\d{4}/);
    return m ? m[0] : raw.replace(/[()]/g, "");
  }

  function refIdFromHref(href) {
    if (!href || href.charAt(0) !== "#") return "";
    return href.slice(1);
  }

  function ensureStatusPopover() {
    if (statusPopover) return statusPopover;
    statusPopover = document.createElement("div");
    statusPopover.id = "as-status-peek";
    statusPopover.className = "as-peek as-peek--status";
    statusPopover.setAttribute("role", "tooltip");
    statusPopover.hidden = true;
    statusPopover.innerHTML =
      '<p class="as-peek__kicker">Evidence status</p>' +
      '<p class="as-peek__term"></p>' +
      '<p class="as-peek__def"></p>' +
      '<p class="as-peek__hint">Label + mark carry meaning; color is only a secondary scan aid.</p>';
    document.body.appendChild(statusPopover);
    return statusPopover;
  }

  function positionPeek(anchor, tip) {
    tip.style.visibility = "hidden";
    tip.hidden = false;
    var rect = anchor.getBoundingClientRect();
    var tipRect = tip.getBoundingClientRect();
    var margin = 10;
    var gap = 10;
    var vw = window.innerWidth;
    var vh = window.innerHeight;
    var narrow = vw < 640;

    var left;
    if (narrow) {
      left = Math.max(margin, (vw - tipRect.width) / 2) + window.scrollX;
    } else {
      left = rect.left + window.scrollX;
      if (left + tipRect.width > window.scrollX + vw - margin) {
        left = window.scrollX + vw - tipRect.width - margin;
      }
      if (left < window.scrollX + margin) left = window.scrollX + margin;
    }

    var spaceBelow = vh - rect.bottom;
    var spaceAbove = rect.top;
    var top;
    if (spaceBelow >= tipRect.height + gap || spaceBelow >= spaceAbove) {
      top = rect.bottom + window.scrollY + gap;
    } else {
      top = rect.top + window.scrollY - tipRect.height - gap;
    }

    tip.style.left = Math.max(0, left) + "px";
    tip.style.top = Math.max(0, top) + "px";
    tip.style.visibility = "";
  }

  /* ---------- 1. Citation peek ---------- */

  function enrichCitePreview(wrap) {
    var cite = wrap.querySelector("a.cite");
    var preview = wrap.querySelector(".cite-preview");
    if (!cite || !preview) return;

    var refId = refIdFromHref(cite.getAttribute("href"));
    var ref = refId ? document.getElementById(refId) : null;
    if (!ref) return;

    var authors = textOf(ref.querySelector(".ref-authors"));
    var year = yearText(ref.querySelector(".ref-year"));
    var title = textOf(ref.querySelector(".ref-title"));
    var journal = venueText(ref.querySelector(".ref-venue"));
    var doi = doiText(ref.querySelector(".ref-doi"));

    if (!authors && !title) return;

    preview.classList.add("cite-preview--rich");
    preview.innerHTML = "";

    if (authors) {
      var a = document.createElement("span");
      a.className = "cite-preview__authors";
      a.textContent = authors;
      preview.appendChild(a);
    }
    if (year) {
      var y = document.createElement("span");
      y.className = "cite-preview__year";
      y.textContent = year;
      preview.appendChild(y);
    }
    if (title) {
      var t = document.createElement("span");
      t.className = "cite-preview__title";
      t.textContent = title;
      preview.appendChild(t);
    }
    if (journal) {
      var j = document.createElement("span");
      j.className = "cite-preview__journal";
      j.textContent = journal;
      preview.appendChild(j);
    }
    if (doi) {
      var d = document.createElement("span");
      d.className = "cite-preview__doi";
      d.textContent = "DOI " + doi;
      preview.appendChild(d);
    }

    var foot = document.createElement("span");
    foot.className = "cite-preview__foot";
    foot.textContent = canHover
      ? "Click citation to open full reference."
      : "Tap citation again to open full reference.";
    preview.appendChild(foot);
  }

  function closeCitePeek() {
    if (!openCiteWrap) return;
    openCiteWrap.classList.remove("is-cite-open");
    openCiteWrap = null;
  }

  function openCitePeek(wrap) {
    if (openCiteWrap && openCiteWrap !== wrap) closeCitePeek();
    wrap.classList.add("is-cite-open");
    openCiteWrap = wrap;
  }

  function initCitationPeeks() {
    /* Wrap bare a.cite that lack .cite-wrap (progressive enhancement) */
    Array.prototype.forEach.call(document.querySelectorAll("a.cite[href^='#ref-']"), function (cite) {
      if (cite.closest(".cite-wrap")) return;
      if (cite.closest(".ref-list")) return;
      if (cite.closest(".technical-sources")) return;
      var wrap = document.createElement("span");
      wrap.className = "cite-wrap";
      cite.parentNode.insertBefore(wrap, cite);
      wrap.appendChild(cite);
      var preview = document.createElement("span");
      preview.className = "cite-preview";
      preview.setAttribute("role", "tooltip");
      var pid = "cite-preview-auto-" + (cite.id || Math.random().toString(36).slice(2, 9));
      preview.id = pid;
      preview.textContent = "Full entry in References.";
      wrap.appendChild(preview);
      if (!cite.getAttribute("aria-describedby")) {
        cite.setAttribute("aria-describedby", pid);
      }
    });

    var wraps = document.querySelectorAll(".cite-wrap");
    if (!wraps.length) return;

    Array.prototype.forEach.call(wraps, function (wrap) {
      enrichCitePreview(wrap);

      var cite = wrap.querySelector("a.cite");
      if (!cite) return;

      if (!canHover) {
        cite.addEventListener("click", function (event) {
          if (wrap.classList.contains("is-cite-open")) {
            closeCitePeek();
            return;
          }
          event.preventDefault();
          openCitePeek(wrap);
        });
      }

      cite.addEventListener("keydown", function (event) {
        if (event.key === "Escape") {
          event.preventDefault();
          closeCitePeek();
        }
      });
    });

    document.addEventListener("click", function (event) {
      if (!openCiteWrap) return;
      if (openCiteWrap.contains(event.target)) return;
      closeCitePeek();
    });

    document.addEventListener("keydown", function (event) {
      if (event.key === "Escape") closeCitePeek();
    });
  }

  /* ---------- 4. Evidence status peek ---------- */

  function statusKeyFromEl(el) {
    var classes = el.className || "";
    var keys = Object.keys(STATUS_DEFS);
    for (var i = 0; i < keys.length; i++) {
      if (classes.indexOf("ev-status--" + keys[i]) !== -1) return keys[i];
    }
    var data = (el.getAttribute("data-status") || "").toLowerCase();
    if (STATUS_DEFS[data]) return data;
    return "";
  }

  function closeStatusPeek() {
    if (statusHoverTimer) {
      window.clearTimeout(statusHoverTimer);
      statusHoverTimer = null;
    }
    if (!statusPopover || !activeStatus) return;
    statusPopover.hidden = true;
    activeStatus.setAttribute("aria-expanded", "false");
    activeStatus.removeAttribute("aria-describedby");
    activeStatus = null;
  }

  function openStatusPeek(el) {
    var key = statusKeyFromEl(el);
    var entry = STATUS_DEFS[key];
    if (!entry) return;

    var tip = ensureStatusPopover();
    if (activeStatus && activeStatus !== el) {
      activeStatus.setAttribute("aria-expanded", "false");
      activeStatus.removeAttribute("aria-describedby");
    }

    tip.querySelector(".as-peek__term").textContent = entry.label;
    tip.querySelector(".as-peek__def").textContent = entry.def;
    tip.hidden = false;

    el.setAttribute("aria-expanded", "true");
    el.setAttribute("aria-describedby", tip.id);
    activeStatus = el;
    positionPeek(el, tip);
  }

  function initStatusPeeks() {
    var chips = document.querySelectorAll(
      ".ev-status:not(.ev-status--block), .evidence-status[data-status]"
    );
    if (!chips.length) return;

    ensureStatusPopover();

    Array.prototype.forEach.call(chips, function (el) {
      if (el.closest(".ev-status-legend")) return;
      if (el.querySelector(".ev-status__desc")) return;
      if (!statusKeyFromEl(el)) return;

      if (!el.hasAttribute("tabindex")) el.setAttribute("tabindex", "0");
      el.setAttribute("role", "button");
      el.setAttribute("aria-expanded", "false");
      el.classList.add("ev-status--peekable");

      var label = el.querySelector(".ev-status__label");
      var name = label ? textOf(label) : statusKeyFromEl(el).toUpperCase();
      if (!el.getAttribute("aria-label")) {
        el.setAttribute("aria-label", "Evidence status: " + name + ". Activate for definition.");
      }

      el.addEventListener("mouseenter", function () {
        if (!canHover) return;
        statusHoverTimer = window.setTimeout(function () {
          openStatusPeek(el);
        }, 80);
      });

      el.addEventListener("mouseleave", function () {
        if (statusHoverTimer) {
          window.clearTimeout(statusHoverTimer);
          statusHoverTimer = null;
        }
        if (document.activeElement !== el) closeStatusPeek();
      });

      el.addEventListener("focus", function () {
        openStatusPeek(el);
      });

      el.addEventListener("blur", function () {
        window.setTimeout(function () {
          if (activeStatus === el && document.activeElement !== el) {
            closeStatusPeek();
          }
        }, 0);
      });

      el.addEventListener("click", function (event) {
        event.preventDefault();
        if (activeStatus === el && statusPopover && !statusPopover.hidden) {
          closeStatusPeek();
        } else {
          openStatusPeek(el);
        }
      });

      el.addEventListener("keydown", function (event) {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          if (activeStatus === el && statusPopover && !statusPopover.hidden) {
            closeStatusPeek();
          } else {
            openStatusPeek(el);
          }
        } else if (event.key === "Escape") {
          event.preventDefault();
          closeStatusPeek();
          el.focus();
        }
      });
    });

    document.addEventListener("keydown", function (event) {
      if (event.key === "Escape") {
        var prev = activeStatus;
        closeStatusPeek();
        if (prev) prev.focus();
      }
    });

    document.addEventListener("click", function (event) {
      if (!activeStatus) return;
      var tip = ensureStatusPopover();
      if (activeStatus.contains(event.target) || tip.contains(event.target)) return;
      closeStatusPeek();
    });

    window.addEventListener(
      "scroll",
      function () {
        if (activeStatus && statusPopover && !statusPopover.hidden) {
          positionPeek(activeStatus, statusPopover);
        }
      },
      { passive: true }
    );

    window.addEventListener("resize", function () {
      if (activeStatus && statusPopover && !statusPopover.hidden) {
        positionPeek(activeStatus, statusPopover);
      }
    });
  }

  /* ---------- 3. What to notice ---------- */

  function initNotices() {
    var notices = document.querySelectorAll(".as-notice, details.wiki-figure__notice");
    Array.prototype.forEach.call(notices, function (el) {
      el.classList.add("as-notice");
      var list = el.querySelector("ol, ul");
      if (!list) return;
      var items = list.children;
      var count = 0;
      for (var i = 0; i < items.length; i++) {
        if (items[i].tagName !== "LI") continue;
        count += 1;
        if (count > 3) items[i].hidden = true;
      }
      if (count > 3) {
        el.setAttribute("data-as-notice-capped", "3");
      }
    });
  }

  /* ---------- 5. Before ↔ After ---------- */

  function initCompareRoot(root) {
    var tabs = root.querySelectorAll("[data-as-compare-btn]");
    var panels = root.querySelectorAll("[data-as-compare-panel]");
    var live = root.querySelector("[data-as-compare-live]");
    if (tabs.length < 2 || panels.length < 2) return;

    root.classList.add("is-enhanced");

    function show(key, announce) {
      Array.prototype.forEach.call(tabs, function (tab) {
        var on = tab.getAttribute("data-as-compare-btn") === key;
        tab.classList.toggle("is-active", on);
        tab.setAttribute("aria-selected", on ? "true" : "false");
        tab.tabIndex = on ? 0 : -1;
      });
      Array.prototype.forEach.call(panels, function (panel) {
        var on = panel.getAttribute("data-as-compare-panel") === key;
        panel.classList.toggle("is-active", on);
        if (on) {
          panel.removeAttribute("hidden");
        } else {
          panel.setAttribute("hidden", "");
        }
      });
      if (announce && live) {
        var activeTab = root.querySelector('[data-as-compare-btn="' + key + '"]');
        live.textContent = activeTab ? textOf(activeTab) : key;
      }
    }

    Array.prototype.forEach.call(tabs, function (tab, index) {
      tab.addEventListener("click", function () {
        show(tab.getAttribute("data-as-compare-btn"), true);
      });

      tab.addEventListener("keydown", function (event) {
        var next = null;
        if (event.key === "ArrowRight" || event.key === "ArrowDown") {
          next = tabs[(index + 1) % tabs.length];
        } else if (event.key === "ArrowLeft" || event.key === "ArrowUp") {
          next = tabs[(index - 1 + tabs.length) % tabs.length];
        } else if (event.key === "Home") {
          next = tabs[0];
        } else if (event.key === "End") {
          next = tabs[tabs.length - 1];
        }
        if (!next) return;
        event.preventDefault();
        next.focus();
        show(next.getAttribute("data-as-compare-btn"), true);
      });
    });

    var initial =
      root.querySelector('[data-as-compare-btn][aria-selected="true"]') || tabs[0];
    show(initial.getAttribute("data-as-compare-btn"), false);

    if (reduceMotion) {
      root.classList.add("as-compare--static");
    }
  }

  function initCompares() {
    Array.prototype.forEach.call(
      document.querySelectorAll("[data-as-compare]"),
      initCompareRoot
    );
  }

  /* ---------- 6. Follow the evidence ---------- */

  function initEvidenceTrails() {
    var trails = document.querySelectorAll(".as-evidence-trail, .evidence-links");
    Array.prototype.forEach.call(trails, function (trail) {
      trail.classList.add("as-evidence-trail");
      var page = (document.body.className.match(/page-[\w-]+/) || [])[0] || "";
      var links = trail.querySelectorAll("a[href]");
      Array.prototype.forEach.call(links, function (link) {
        var href = (link.getAttribute("href") || "").split("#")[0];
        if (!href) return;
        var file = href.replace(/^\.\//, "");
        if (
          (page === "page-design" && /design\.html$/i.test(file)) ||
          (page === "page-experiments" && /experiments\.html$/i.test(file)) ||
          (page === "page-results" && /results\.html$/i.test(file)) ||
          (page === "page-engineering" && /engineering\.html$/i.test(file)) ||
          (page === "page-notebook" && /notebook\.html$/i.test(file)) ||
          (page === "page-hardware" && /hardware\.html$/i.test(file))
        ) {
          link.setAttribute("aria-current", "page");
        }
      });
    });
  }

  document.addEventListener("DOMContentLoaded", function () {
    initCitationPeeks();
    initStatusPeeks();
    initNotices();
    initCompares();
    initEvidenceTrails();
  });
})();
